version: '3'
services:
  web:
    build: ./build
    ports:
      - "8080:80"
    container_name: devops_web

services:
     web:
       build: .
       ports:
         - "80:80"
       container_name: react-app
